version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: appdb
    volumes:
      - /mnt/db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "appuser"]
      interval: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    restart: always
    
  django:
    image: django:latest
    container_name: django
    environment:
      DATABASE_URL: postgres://appuser:strongpassword@db:5432/appdb
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000  
    restart: on-failure

